### ISSUE TITLE
Plugin removed "watched" on trakt website

### ISSUE THREAD

**Issue by Rhizix** [jellyfin/jellyfin-plugin-trakt#15]
Installed the plug-in v3.0.0 and ran the scheduled task.
After a few minutes I noticed that almost all of my watch history was deleted from the trakt website.
Jellyfin pushed the watched states (all unwatched) to trakt it seems, instead of the other way around. (Don't think this is supposed to happen?)
Any way to revert this?

**Comment by lindvall** [comment]
I noticed the same issue. Once I realized what it was doing by watching the log I stopped the task immediately.

Unfortunately I don't think there is any way to reverse what have been done, but someone with a better understanding of the Trakt API should answer that.

According to the code there should be another task named "Import playstates from Trakt.tv", but that isn't showing up. Because of that we executed the wrong task and overwrote states from Jellyfin to Trakt.

Why doesn't the task "Import playstates from Trakt.tv" show up in among the scheduled tasks?

**Comment by Rhizix** [comment]
I contacted Trakt support and luckily they were able to revert the changes.
Would also like to know why this issue occurred.

**Comment by lindvall** [comment]
It seems like #17 might fix the issue I mentioned.

**Comment by Agitated-Junk** [comment]
Happened with me also. 

Interestingly version of my trakt plugin is still showing as 2.0.0.0 instead of 3.0.0.0. I've uninstalled and reinstalled the plugin and even tried reinstalling it after removing the whole plugins directory.

**Comment by anthonylavado** [comment]
>Version is still showing as 2.0.0.0...

@Agitated-Junk Yes, we missed one field in the rush to fix it. #17 handles this too.

**Comment by Agitated-Junk** [comment]
@anthonylavado Why there is no task under 'schedule task' for syncing library 'from' trakt? Pardon me if this already been solved, last when i checked, it wasn't there.

**Comment by anthonylavado** [comment]
@agitated-junk This is fixed in #17. It was a change that was missed in the rush to updating things as well.

**Comment by hrvstr** [comment]
How can I update the plugin to get the latest fix? Last time reinstalling did the trick but now it's installing plugin version 2.0.0. again.

**Comment by anthonylavado** [comment]
It has to be rebuilt still. Let me see what I can do

**Comment by kalle-del-haye** [comment]
I get the message that Trakt was updated to version 3.0 after **every** check for plugin updates. Multiple times since yesterday.

The plugins page still shows version 2.0.0.0 for Trakt.
And the sync from Trakt task is still missing on the scheduled tasks page.

So, something is wrong with the last update, i think.
Or do I have to remove the old plugin from the Jellyfin folder by hand?

**Comment by anthonylavado** [comment]
@kalle-del-haye We didn’t update the version in all places, so installing 3.0.0 shows up as 2.0.0 in the system. We’ll be releasing 4.0.0 to avoid confusion, shortly.

**Comment by anthonylavado** [comment]
All - 4.0.0 is now live. Please test and let me know.

**Comment by kalle-del-haye** [comment]
There was still the old version of Trakt plugin in /var/lib/jellyfin/plugins/jellyfin-plugin-trakt_1.0.0 (Devuan server [Debian based]). After removing it by hand and reinstalling the v4.0 all works as expected. But not sure if it was necessary.

So, thanks a lot for your quick help.

By the way, why is the old plugin directory not deleted by Jellyfin? Old plugin versions are still in there (jellyfin-plugin-kodisyncqueue_1.0.0, jellyfin-plugin-tmdbboxsets_1.0.0). Can I delete the /var/lib/jellyfin/plugins/ folder?

**Comment by hrvstr** [comment]
Working fine here! I manually uninstalled, restarted the service, installed the plugin and did another restart. All scheduled jobs are showing up and all watch states have successfully been imported!

**Comment by anthonylavado** [comment]
@kalle-del-hate I think it was done to leave installations as they were, if needed. You’re likely safe to delete that folder.
