### ISSUE TITLE
[Issue]:  possible bug with trakt plugin

### ISSUE THREAD

**Issue by RiaanPretoriusSA** [jellyfin/jellyfin-plugin-trakt#160]
### Please describe your bug

Not sure if this is the right place to log a bug or if it is a bug. but if more then one user is authorized the plugin complains about this:  `Trakt.Api.TraktApi: Tried to reauthenticate with Trakt, but no refreshToken was available`. So when I de-authed all other users except one the plugin ran perfect. 

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: raspbian 64bit / PI4
- Virtualization: docker
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
I only experienced this when upgrading from an old version of the plugin where we didn't properly save and re-issue the refresh token. De-Authing the user or removing it from `/var/lib/jellyfin/plugins/configuration/Trakt.xml` and re-adding it afterwards should fix it.

**Comment by Appoxo** [comment]
Removing worked for me. De-Auth was a hit-or-miss for me

**Comment by RiaanPretoriusSA** [comment]
Still can't add a second user. Lucky so far I am the only user that want to
sync to trakt. I move between kody and JFin. Might be a good idea for the
developer to maybe consider something like trakt.xml.<username>. Could just
be a bug with trakt itself. But after struggling more then a week with
this, I started to play around and got it to work with a single user and
de-authentication
